"""add password column in users table that stores passwords

Revision ID: 52cdef52f382
Revises: 4f3e2ea2f816
Create Date: 2019-10-28 10:02:23.507083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cdef52f382'
down_revision = '4f3e2ea2f816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###
